### ISSUE TITLE
undefined method `on_load' for ActiveSupport:Module

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-output-email#37]
Logstash >= 2.2.0 won't start with the following config:

```
input {
 stdin {

 }
}

output {
 email {
     to             =>    "you@gmail.com"
 }
 stdout { codec => rubydebug }
}
```
2.2.0 throws:

```
The error reported is:
  undefined method `on_load' for ActiveSupport:Module
```

2.3.1 throws:
```
Pipeline aborted due to error {:exception=>#<NoMethodError: undefined method `on_load' for ActiveSupport:Module>, :backtrace=>["/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/awesome_print-1.6.1/lib/awesome_print.rb:29:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.7/lib/logstash/codecs/rubydebug.rb:1:in `(root)'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.7/lib/logstash/codecs/rubydebug.rb:18:in `register'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/codecs/base.rb:15:in `initialize'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/config/mixin.rb:427:in `validate_value'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/config/mixin.rb:368:in `validate_check_parameter_values'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/config/mixin.rb:363:in `validate_check_parameter_values'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/config/mixin.rb:362:in `validate_check_parameter_values'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/config/mixin.rb:277:in `validate'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/config/mixin.rb:133:in `config_init'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/outputs/base.rb:63:in `initialize'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:74:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/Users/jay/Workspace/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:136:in `run'"], :level=>:error}
```

When you remove 
` stdout { codec => rubydebug }`, it works!  Weird eh?

This might explain it:
https://github.com/nu7hatch/gmail/issues/132

**Comment by gerrywastaken** [comment]
I believe Mail 2.6.4 fixed this issue: https://github.com/mikel/mail/pull/830#discussion-diff-45785453L394

**Comment by wiibaa** [comment]
@gerrywastaken the mail version was fixed to 2.6.3 due to jruby is compatible with "1.9" that is dropped by an update of a dependency of mail as discovered in https://github.com/elastic/logstash/issues/4883

**Comment by gerrywastaken** [comment]
@wiibaa Ok, well there is a fix in master on awesome_print for this issue: https://github.com/michaeldv/awesome_print/pull/200

However I don't yet have access to push a release to rubygems.org: https://github.com/michaeldv/awesome_print/issues/234

**Comment by gerrywastaken** [comment]
Ok the fix has now been pushed to Rubygems as version 1.7.0. Thanks for your help with this. :)
